"""
Graph 심화 (1) — 커스텀 함수 노드

Agent가 아닌 '일반 파이썬 함수'를 그래프 노드로 사용하는 방법.
LLM 호출 없이 결정적인 로직(검증·포맷팅 등)을 그래프 안에 넣을 때 유용하다.

흐름: validate(함수) -> process(Agent) -> format(함수)
"""

from strands import Agent
from strands.multiagent import GraphBuilder
from strands.multiagent.base import MultiAgentBase, MultiAgentResult, Status, NodeResult
from strands.agent.agent_result import AgentResult
from strands.types.content import ContentBlock, Message


class FunctionNode(MultiAgentBase):
    """결정적인 파이썬 함수를 그래프 노드로 실행하는 래퍼."""

    def __init__(self, func, name: str = None):
        super().__init__()
        self.func = func
        self.name = name or func.__name__

    async def invoke_async(self, task, invocation_state, **kwargs):
        output = self.func(task if isinstance(task, str) else str(task))

        agent_result = AgentResult(
            stop_reason="end_turn",
            message=Message(role="assistant", content=[ContentBlock(text=str(output))]),
            metrics=None,
            state={},
        )
        return MultiAgentResult(
            status=Status.COMPLETED,
            results={self.name: NodeResult(result=agent_result)},
        )


def validate_input(text: str) -> str:
    """입력 형식 검증."""
    if len(text) < 10:
        raise ValueError("Input too short - must be at least 10 characters")
    return f"[VALIDATED] {text}"


def format_output(text: str) -> str:
    """최종 출력 포맷팅."""
    return f"=== FINAL REPORT ===\n{text}\n(Generated by Multi-Agent Graph)"


def run_custom_nodes():
    """흐름: validate(함수) -> process(Agent) -> format(함수)"""
    processor = Agent(name="processor", system_prompt="You summarize the given topic concisely.")

    builder = GraphBuilder()
    builder.add_node(FunctionNode(validate_input, "validate"), "validate")
    builder.add_node(processor, "process")
    builder.add_node(FunctionNode(format_output, "format"), "format")

    builder.add_edge("validate", "process")
    builder.add_edge("process", "format")
    builder.set_entry_point("validate")

    result = builder.build()("Summarize quantum computing applications")
    print(f"[커스텀 노드] status={result.status}, "
          f"order={[n.node_id for n in result.execution_order]}")


if __name__ == "__main__":
    run_custom_nodes()
