"""
Graph 심화 패턴 (main.py의 기초 흐름을 먼저 이해한 뒤 볼 것).

세 가지 심화 기법을 다룬다:
    1. 커스텀 함수 노드   - Agent가 아닌 일반 파이썬 함수를 노드로 사용
    2. Swarm 합성         - Swarm을 하나의 그래프 노드로 사용 (패턴 조합)
    3. 조건부 엣지        - 리뷰 결과에 따라 분기/반복하는 흐름
"""

from strands import Agent
from strands.multiagent import GraphBuilder, Swarm
from strands.multiagent.graph import GraphState
from strands.multiagent.base import MultiAgentBase, MultiAgentResult, Status, NodeResult
from strands.agent.agent_result import AgentResult
from strands.types.content import ContentBlock, Message


# ============================================================================
# 1. 커스텀 함수 노드 - Agent 대신 일반 파이썬 함수를 노드로 실행
# ============================================================================
class FunctionNode(MultiAgentBase):
    """결정적인 파이썬 함수를 그래프 노드로 실행하는 래퍼."""

    def __init__(self, func, name: str = None):
        super().__init__()
        self.func = func
        self.name = name or func.__name__

    async def invoke_async(self, task, invocation_state, **kwargs):
        output = self.func(task if isinstance(task, str) else str(task))

        agent_result = AgentResult(
            stop_reason="end_turn",
            message=Message(role="assistant", content=[ContentBlock(text=str(output))]),
            metrics=None,
            state={},
        )
        return MultiAgentResult(
            status=Status.COMPLETED,
            results={self.name: NodeResult(result=agent_result)},
        )


def validate_input(text: str) -> str:
    """입력 형식 검증."""
    if len(text) < 10:
        raise ValueError("Input too short - must be at least 10 characters")
    return f"[VALIDATED] {text}"


def format_output(text: str) -> str:
    """최종 출력 포맷팅."""
    return f"=== FINAL REPORT ===\n{text}\n(Generated by Multi-Agent Graph)"


def run_custom_nodes():
    """흐름: validate(함수) -> process(Agent) -> format(함수)"""
    processor = Agent(name="processor", system_prompt="You summarize the given topic concisely.")

    builder = GraphBuilder()
    builder.add_node(FunctionNode(validate_input, "validate"), "validate")
    builder.add_node(processor, "process")
    builder.add_node(FunctionNode(format_output, "format"), "format")

    builder.add_edge("validate", "process")
    builder.add_edge("process", "format")
    builder.set_entry_point("validate")

    result = builder.build()("Summarize quantum computing applications")
    print(f"[커스텀 노드] status={result.status}, "
          f"order={[n.node_id for n in result.execution_order]}")


# ============================================================================
# 2. Swarm 합성 - Swarm 자체를 하나의 그래프 노드로 사용
# ============================================================================
def run_swarm_as_node():
    """흐름: Swarm(탐색 연구) -> verify(Agent) -> finalize(Agent)"""
    researcher = Agent(name="researcher", system_prompt="You gather information on topics.")
    analyst = Agent(name="analyst", system_prompt="You analyze data and provide insights.")
    fact_checker = Agent(name="fact_checker", system_prompt="You verify facts and accuracy.")
    report_writer = Agent(name="report_writer", system_prompt="You create clear reports.")

    research_swarm = Swarm([researcher, analyst], entry_point=researcher, max_handoffs=5)

    builder = GraphBuilder()
    builder.add_node(research_swarm, "exploratory_research")
    builder.add_node(fact_checker, "verify")
    builder.add_node(report_writer, "finalize")

    builder.add_edge("exploratory_research", "verify")
    builder.add_edge("verify", "finalize")
    builder.set_entry_point("exploratory_research")

    result = builder.build()("Research emerging AI trends")
    print(f"[Swarm 합성] status={result.status}")


# ============================================================================
# 3. 조건부 엣지 - 리뷰 결과에 따라 분기하거나 반복(loop)
# ============================================================================
def quality_check_passed(state: GraphState) -> bool:
    """리뷰 통과 여부 판정."""
    reviewer_result = state.results.get("reviewer")
    if not reviewer_result or reviewer_result.status != Status.COMPLETED:
        return False
    return "APPROVED" in str(reviewer_result.result)


def run_conditional_edges():
    """흐름: writer -> reviewer -> (통과 시 publisher / 미달 시 writer 재작성)"""
    writer = Agent(name="writer", system_prompt="You write content. Include 'DRAFT' in your output.")
    reviewer = Agent(
        name="reviewer",
        system_prompt=(
            "You review content quality. "
            "If good, respond with 'APPROVED: [feedback]'. "
            "If it needs work, respond with 'NEED_REVISION: [feedback]'."
        ),
    )
    publisher = Agent(name="publisher", system_prompt="You publish approved content.")

    builder = GraphBuilder()
    builder.add_node(writer, "writer")
    builder.add_node(reviewer, "reviewer")
    builder.add_node(publisher, "publisher")

    builder.add_edge("writer", "reviewer")
    builder.add_edge("reviewer", "publisher", condition=quality_check_passed)
    builder.add_edge("reviewer", "writer", condition=lambda s: not quality_check_passed(s))

    builder.set_entry_point("writer")
    builder.set_execution_timeout(300)

    result = builder.build()("Write a brief introduction to AI")
    print(f"[조건부 엣지] order={[n.node_id for n in result.execution_order]}")


if __name__ == "__main__":
    run_custom_nodes()
    run_swarm_as_node()
    run_conditional_edges()
